const API='https://ubjsvqhxoufdjwzqkmsd.supabase.co/functions/v1/school-api';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('schoolToken')||'';let student=null;let adminToken=sessionStorage.getItem('adminToken')||'';
async function call(action,extra={},t=token){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({error:'خطای سرور'}));if(!r.ok)throw Error(d.error||'خطا');return d}
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
async function login(){const u=$('username').value.trim(),p=$('password').value;if(!u||!p){$('loginMessage').textContent='نام کاربری و رمز را وارد کنید.';return}try{$('loginMessage').textContent='در حال ورود...';const d=await call('login',{username:u,password:p},'');token=d.token;student=d.student;sessionStorage.setItem('schoolToken',token);$('loginSection').classList.add('hidden');$('adminPanel').classList.add('hidden');$('studentPanel').classList.remove('hidden');await render()}catch(e){$('loginMessage').textContent=e.message}}
async function render(){const me=await call('me');student=me.student;$('studentName').textContent=student.full_name;$('studentPoints').textContent=student.points+' امتیاز';const d=await call('rewards'),grid=$('rewardsGrid');grid.innerHTML='';(d.rewards||[]).forEach(r=>{const card=document.createElement('article');card.className='reward';const can=student.points>=r.points_required&&r.stock>0;card.innerHTML='<div class="emoji">'+esc(r.emoji||'🎁')+'</div><h3>'+esc(r.name)+'</h3><div class="price">'+r.points_required+' امتیاز</div><div class="stock">موجودی: '+r.stock+'</div><br><button '+(can?'':'disabled')+'>'+ (r.stock===0?'ناموجود':can?'دریافت جایزه':'امتیاز کافی نیست')+'</button>';if(can)card.querySelector('button').onclick=()=>claim(r.id);grid.appendChild(card)});await requests()}
async function claim(id){try{const d=await call('request_reward',{reward_id:id});alert('درخواست ثبت شد. امتیاز باقی‌مانده: '+d.result.points_left);await render()}catch(e){alert(e.message)}}
async function requests(){const list=$('requestsList');try{const d=await call('requests');list.innerHTML=(d.requests||[]).length?'':'<p class="empty">هنوز درخواستی ثبت نکرده‌اید.</p>';(d.requests||[]).forEach(x=>{const n=x.rewards?.name||'جایزه';const c=x.rewards?.points_required??'';const s={pending:'در انتظار بررسی',approved:'تأیید شد',rejected:'رد شد',delivered:'تحویل شد'}[x.status]||x.status;const e=document.createElement('div');e.className='request';e.innerHTML='<span>'+esc(n)+' — '+c+' امتیاز</span><span class="status">'+esc(s)+'</span>';list.appendChild(e)})}catch(e){list.innerHTML='<p class="empty">'+esc(e.message)+'</p>'}}
async function adminLogin(){const p=$('adminPassword').value;try{$('adminMessage').textContent='در حال ورود...';const d=await call('admin_login',{username:'admin',password:p},'');adminToken=d.token;sessionStorage.setItem('adminToken',adminToken);$('adminLoginModal').classList.add('hidden');$('loginSection').classList.add('hidden');$('studentPanel').classList.add('hidden');$('adminPanel').classList.remove('hidden');await renderAdmin()}catch(e){$('adminMessage').textContent=e.message}}
async function renderAdmin(){await loadStudents();await loadRewardsAdmin();await loadRequestsAdmin()}
async function loadStudents(){const d=await call('admin_students',{},adminToken);const box=$('studentsAdminList');box.innerHTML=(d.students||[]).map(s=>'<div class="request"><span>'+esc(s.full_name)+' ('+esc(s.username)+') — '+s.points+' امتیاز</span><button onclick="setPoints('+s.id+','+s.points+')">تغییر امتیاز</button></div>').join('')||'<p class="empty">دانش‌آموزی نیست.</p>'}
async function setPoints(id,current){const v=prompt('امتیاز جدید را وارد کنید:',current);if(v===null)return;try{await call('admin_set_points',{student_id:id,points:Number(v)},adminToken);await loadStudents()}catch(e){alert(e.message)}}
async function addStudent(){try{await call('admin_add_student',{username:$('newStudentKey').value,full_name:$('newStudentName').value,password:$('newStudentPassword').value,points:Number($('newStudentPoints').value||0)},adminToken);$('newStudentKey').value='';$('newStudentName').value='';$('newStudentPassword').value='';$('newStudentPoints').value='';alert('دانش‌آموز اضافه شد');await loadStudents()}catch(e){alert(e.message)}}
async function loadRewardsAdmin(){const d=await call('admin_rewards',{},adminToken);$('rewardsAdminList').innerHTML=(d.rewards||[]).map(r=>'<div class="request"><span>'+esc(r.emoji)+' '+esc(r.name)+' — '+r.points_required+' امتیاز — موجودی '+r.stock+'</span></div>').join('')||'<p class="empty">جایزه‌ای نیست.</p>'}
async function addReward(){try{await call('admin_add_reward',{name:$('newRewardName').value,points_required:Number($('newRewardCost').value),stock:Number($('newRewardStock').value),emoji:$('newRewardEmoji').value||'🎁'},adminToken);$('newRewardName').value='';$('newRewardCost').value='';$('newRewardStock').value='';$('newRewardEmoji').value='';alert('جایزه اضافه شد');await loadRewardsAdmin()}catch(e){alert(e.message)}}
async function loadRequestsAdmin(){const d=await call('admin_requests',{},adminToken);const box=$('allRequestsList');box.innerHTML=(d.requests||[]).map(x=>'<div class="request"><span>'+esc(x.students?.full_name||'دانش‌آموز')+' ← '+esc(x.rewards?.name||'جایزه')+' — '+esc(x.status)+'</span><select onchange="setRequestStatus('+x.id+',this.value)"><option value="pending" '+(x.status==='pending'?'selected':'')+'>در انتظار</option><option value="approved" '+(x.status==='approved'?'selected':'')+'>تأیید</option><option value="rejected" '+(x.status==='rejected'?'selected':'')+'>رد</option><option value="delivered" '+(x.status==='delivered'?'selected':'')+'>تحویل شد</option></select></div>').join('')||'<p class="empty">درخواستی وجود ندارد.</p>'}
async function setRequestStatus(id,status){try{await call('admin_request_status',{request_id:id,status},adminToken);await loadRequestsAdmin()}catch(e){alert(e.message)}}
function logout(){token='';student=null;sessionStorage.removeItem('schoolToken');$('studentPanel').classList.add('hidden');$('adminPanel').classList.add('hidden');$('loginSection').classList.remove('hidden');$('username').value='';$('password').value='';$('loginMessage').textContent=''}
function adminLogout(){adminToken='';sessionStorage.removeItem('adminToken');$('adminPanel').classList.add('hidden');$('loginSection').classList.remove('hidden')}
$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('adminOpenBtn').onclick=()=>$('adminLoginModal').classList.remove('hidden');$('modalClose').onclick=()=>$('adminLoginModal').classList.add('hidden');$('adminLoginBtn').onclick=adminLogin;$('adminLogoutBtn').onclick=adminLogout;$('addStudentBtn').onclick=addStudent;$('addRewardBtn').onclick=addReward;
$('username').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
if(token){$('loginSection').classList.add('hidden');$('studentPanel').classList.remove('hidden');render().catch(logout)}else if(adminToken){$('loginSection').classList.add('hidden');$('adminPanel').classList.remove('hidden');renderAdmin().catch(adminLogout)}