const API='https://ubjsvqhxoufdjwzqkmsd.supabase.co/functions/v1/school-api';
const $=id=>document.getElementById(id);let token=sessionStorage.getItem('schoolToken')||'';let student=null;let adminToken=sessionStorage.getItem('adminToken')||'';
async function call(action,extra={},t=token){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})},body:JSON.stringify({action,...extra})});const d=await r.json().catch(()=>({error:'خطای سرور'}));if(!r.ok)throw Error(d.error||'خطا');return d}
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
async function login(){const u=$('username').value.trim(),p=$('password').value;if(!u||!p){$('loginMessage').textContent='نام کاربری و رمز را وارد کنید.';return}try{$('loginMessage').textContent='در حال ورود...';const d=await call('login',{username:u,password:p},'');token=d.token;student=d.student;sessionStorage.setItem('schoolToken',token);$('loginSection').classList.add('hidden');$('adminPanel').classList.add('hidden');$('studentPanel').classList.remove('hidden');await render()}catch(e){$('loginMessage').textContent=e.message}}
async function render(){const me=await call('me');student=me.student;$('studentName').textContent=student.full_name;$('studentPoints').textContent=student.points+' امتیاز';const d=await call('rewards'),grid=$('rewardsGrid');grid.innerHTML='';(d.rewards||[]).forEach(r=>{const card=document.createElement('article');card.className='reward';const can=student.points>=r.points_required&&r.stock>0;card.innerHTML=(r.image_url?'<img src="'+esc(r.image_url)+'" alt="'+esc(r.name)+'" style="width:100%;height:170px;object-fit:cover;border-radius:14px;margin-bottom:10px">':'<div class="emoji">'+esc(r.emoji||'🎁')+'</div>')+'<h3>'+esc(r.name)+'</h3><div class="price">'+r.points_required+' امتیاز</div><div class="stock">موجودی: '+r.stock+'</div><br><button '+(can?'':'disabled')+'>'+ (r.stock===0?'ناموجود':can?'دریافت جایزه':'امتیاز کافی نیست')+'</button>';if(can)card.querySelector('button').onclick=()=>claim(r.id);grid.appendChild(card)});await requests()}
async function claim(id){try{const d=await call('request_reward',{reward_id:id});alert('درخواست ثبت شد. امتیاز باقی‌مانده: '+d.result.points_left);await render()}catch(e){alert(e.message)}}
async function requests(){const list=$('requestsList');try{const d=await call('requests');list.innerHTML=(d.requests||[]).length?'':'<p class="empty">هنوز درخواستی ثبت نکرده‌اید.</p>';(d.requests||[]).forEach(x=>{const n=x.rewards?.name||'جایزه';const c=x.rewards?.points_required??'';const s={pending:'در انتظار بررسی',approved:'تأیید شد',rejected:'رد شد',delivered:'تحویل شد'}[x.status]||x.status;const e=document.createElement('div');e.className='request';e.innerHTML='<span>'+esc(n)+' — '+c+' امتیاز</span><span class="status">'+esc(s)+'</span>';list.appendChild(e)})}catch(e){list.innerHTML='<p class="empty">'+esc(e.message)+'</p>'}}
async function adminLogin(){const u=$('adminUsername').value.trim(),p=$('adminPassword').value;if(!u||!p){$('adminMessage').textContent='نام کاربری و رمز مدیر را وارد کنید.';return}try{$('adminMessage').textContent='در حال ورود...';const d=await call('admin_login',{username:u,password:p},'');adminToken=d.token;sessionStorage.setItem('adminToken',adminToken);$('adminLoginModal').classList.add('hidden');$('loginSection').classList.add('hidden');$('studentPanel').classList.add('hidden');$('adminPanel').classList.remove('hidden');await renderAdmin()}catch(e){$('adminMessage').textContent=e.message}}
async function renderAdmin(){await loadStudents();await loadRewardsAdmin();await loadRequestsAdmin()}
async function loadStudents(){const d=await call('admin_students',{},adminToken);const box=$('studentsAdminList');box.innerHTML=(d.students||[]).map(s=>'<div class="request"><span>'+esc(s.full_name)+' ('+esc(s.username)+') — '+s.points+' امتیاز</span><span><button onclick="editStudent('+s.id+','+JSON.stringify(s.full_name)+','+JSON.stringify(s.username)+')">✏️ ویرایش</button> <button onclick="setPoints('+s.id+','+s.points+')">⭐ امتیاز</button> <button onclick="deleteStudent('+s.id+')">🗑️ حذف</button></span></div>').join('')||'<p class="empty">دانش‌آموزی نیست.</p>'}
async function setPoints(id,current){const v=prompt('امتیاز جدید را وارد کنید:',current);if(v===null)return;const n=Number(v);if(!Number.isInteger(n)||n<0)return alert('امتیاز نامعتبر است');try{await call('admin_set_points',{student_id:id,points:n},adminToken);await loadStudents()}catch(e){alert(e.message)}}
async function editStudent(id,name,user){const newName=prompt('نام و نام خانوادگی:',name);if(newName===null)return;const newUser=prompt('نام کاربری:',user);if(newUser===null)return;const newPass=prompt('رمز جدید (خالی = بدون تغییر):','');if(newPass===null)return;try{await call('admin_update_student',{student_id:id,full_name:newName,username:newUser,password:newPass},adminToken);alert('اطلاعات دانش‌آموز ویرایش شد');await loadStudents()}catch(e){alert(e.message)}}
async function deleteStudent(id){if(!confirm('این دانش‌آموز حذف شود؟ این کار قابل برگشت نیست.'))return;try{await call('admin_delete_student',{student_id:id},adminToken);await loadStudents()}catch(e){alert(e.message)}}
async function addStudent(){try{await call('admin_add_student',{username:$('newStudentKey').value,full_name:$('newStudentName').value,password:$('newStudentPassword').value,points:Number($('newStudentPoints').value||0)},adminToken);$('newStudentKey').value='';$('newStudentName').value='';$('newStudentPassword').value='';$('newStudentPoints').value='';alert('دانش‌آموز اضافه شد');await loadStudents()}catch(e){alert(e.message)}}
async function loadRewardsAdmin(){const d=await call('admin_rewards',{},adminToken);$('rewardsAdminList').innerHTML=(d.rewards||[]).map(r=>'<div class="request">'+(r.image_url?'<img src="'+esc(r.image_url)+'" style="width:54px;height:54px;object-fit:cover;border-radius:10px;margin-left:8px">':'')+'<span>'+esc(r.emoji)+' '+esc(r.name)+' — '+r.points_required+' امتیاز — موجودی '+r.stock+'</span><span><button onclick="editReward('+r.id+','+JSON.stringify(r.name)+','+r.points_required+','+r.stock+','+JSON.stringify(r.emoji||'🎁')+')">✏️ ویرایش</button> <button onclick="deleteReward('+r.id+')">🗑️ حذف</button></span></div>').join('')||'<p class="empty">جایزه‌ای نیست.</p>'}
async function fileToDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>5*1024*1024)return reject(Error('حجم عکس بیشتر از ۵ مگابایت است.'));if(!file.type.startsWith('image/'))return reject(Error('فقط فایل تصویری مجاز است.'));const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(Error('خواندن عکس ناموفق بود.'));fr.readAsDataURL(file)})}
$('newRewardImage').onchange=()=>{const f=$('newRewardImage').files[0],p=$('imagePreview');if(!f){p.innerHTML='';return}p.innerHTML='<img src="'+URL.createObjectURL(f)+'" style="max-width:180px;max-height:140px;border-radius:12px;margin-top:8px">'};
async function addReward(){try{const file=$('newRewardImage').files[0];const image_data=await fileToDataUrl(file);await call('admin_add_reward',{name:$('newRewardName').value,points_required:Number($('newRewardCost').value),stock:Number($('newRewardStock').value),emoji:$('newRewardEmoji').value||'🎁',image_data},adminToken);$('newRewardName').value='';$('newRewardCost').value='';$('newRewardStock').value='';$('newRewardEmoji').value='';$('newRewardImage').value='';$('imagePreview').innerHTML='';alert('جایزه و عکس آن با موفقیت اضافه شد');await loadRewardsAdmin()}catch(e){alert(e.message)}}
async function editReward(id,name,cost,stock,emoji){const n=prompt('نام جایزه:',name);if(n===null)return;const c=prompt('امتیاز لازم:',cost);if(c===null)return;const s=prompt('موجودی:',stock);if(s===null)return;const em=prompt('ایموجی:',emoji);if(em===null)return;try{await call('admin_update_reward',{reward_id:id,name:n,points_required:Number(c),stock:Number(s),emoji:em},adminToken);alert('جایزه ویرایش شد');await loadRewardsAdmin()}catch(e){alert(e.message)}}
async function deleteReward(id){if(!confirm('این جایزه حذف شود؟ اگر درخواست مرتبط داشته باشد ممکن است حذف نشود.'))return;try{await call('admin_delete_reward',{reward_id:id},adminToken);await loadRewardsAdmin()}catch(e){alert(e.message)}}
async function loadRequestsAdmin(){const d=await call('admin_requests',{},adminToken);const box=$('allRequestsList');box.innerHTML=(d.requests||[]).map(x=>'<div class="request"><span>'+esc(x.students?.full_name||'دانش‌آموز')+' ← '+esc(x.rewards?.name||'جایزه')+' — '+esc(x.status)+'</span><select onchange="setRequestStatus('+x.id+',this.value)"><option value="pending" '+(x.status==='pending'?'selected':'')+'>در انتظار</option><option value="approved" '+(x.status==='approved'?'selected':'')+'>تأیید</option><option value="rejected" '+(x.status==='rejected'?'selected':'')+'>رد</option><option value="delivered" '+(x.status==='delivered'?'selected':'')+'>تحویل شد</option></select></div>').join('')||'<p class="empty">درخواستی وجود ندارد.</p>'}
async function setRequestStatus(id,status){try{await call('admin_request_status',{request_id:id,status},adminToken);await loadRequestsAdmin()}catch(e){alert(e.message)}}
function logout(){token='';student=null;sessionStorage.removeItem('schoolToken');$('studentPanel').classList.add('hidden');$('adminPanel').classList.add('hidden');$('loginSection').classList.remove('hidden');$('username').value='';$('password').value='';$('loginMessage').textContent=''}
function adminLogout(){adminToken='';sessionStorage.removeItem('adminToken');$('adminPanel').classList.add('hidden');$('loginSection').classList.remove('hidden')}
$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('adminOpenBtn').onclick=()=>$('adminLoginModal').classList.remove('hidden');$('modalClose').onclick=()=>$('adminLoginModal').classList.add('hidden');$('adminLoginBtn').onclick=adminLogin;$('adminLogoutBtn').onclick=adminLogout;$('addStudentBtn').onclick=addStudent;$('addRewardBtn').onclick=addReward;
$('username').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('adminUsername').addEventListener('keydown',e=>{if(e.key==='Enter')$('adminPassword').focus()});$('adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin()});
if(token){$('loginSection').classList.add('hidden');$('studentPanel').classList.remove('hidden');render().catch(logout)}else if(adminToken){$('loginSection').classList.add('hidden');$('adminPanel').classList.remove('hidden');renderAdmin().catch(adminLogout)}